import type { Theme } from "./store";

export type BuiltInTheme = {
  id: string;
  name: string;
  category: string;
  description: string;
  bgImageUrl: string;
  theme: Theme;
};

export const BUILT_IN_THEMES: BuiltInTheme[] = [
  {
    id: "blue-box-pattern",
    name: "Blue Box",
    category: "Geometric",
    description: "Geometric blue box vector pattern with contrasting elements.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/bluebox.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/bluebox.svg') center / cover no-repeat #1e40af",
      card: "rgba(255, 255, 255, 0.92)",
      text: "#1e3a8a",
      button: "pill",
      buttonBg: "#fbbf24",
      buttonText: "#1e3a8a",
      font: "sans",
      nameFont: "bungee",
      bioFont: "ubuntu",
    },
  },
  {
    id: "crazy-drive-pattern",
    name: "Crazy Drive",
    category: "Pop Art",
    description: "Dynamic high-energy vector drive pattern with bold neon contrast.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/crazy%20drive.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/crazy%20drive.svg') center / cover no-repeat #0d1117",
      card: "rgba(255, 255, 255, 0.92)",
      text: "#000000",
      button: "pill",
      buttonBg: "#f43f5e",
      buttonText: "#000000",
      font: "display",
      nameFont: "marker",
      bioFont: "comfortaa",
    },
  },
  {
    id: "alpine-mountain-pattern",
    name: "Alpine Mountain",
    category: "Nature",
    description: "Scenic mountain landscape vector artwork background.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/mountain.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/mountain.svg') center / cover no-repeat #0b132b",
      card: "rgba(255, 255, 255, 0.92)",
      text: "#000000",
      button: "pill",
      buttonBg: "#ffffff",
      buttonText: "#000000",
      font: "oswald",
      nameFont: "oswald",
      bioFont: "oswald",
    },
  },

  {
    id: "denim-jeans-pattern",
    name: "Denim Jeans",
    category: "Abstract",
    description: "Classic blue denim jeans vector pattern texture.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/jeans.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/jeans.svg') center / cover no-repeat #0f172a",
      card: "rgba(255, 255, 255, 0.92)",
      text: "#0f172a",
      button: "pill",
      buttonBg: "#38bdf8",
      buttonText: "#0f172a",
      font: "ubuntu",
      nameFont: "ubuntu",
      bioFont: "ubuntu",
    },
  },
  {
    id: "fluid-wave-pattern",
    name: "Fluid Wave Pattern",
    category: "Abstract",
    description: "Custom fluid wave artwork with smooth organic curves.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/file.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/file.svg') center / cover no-repeat #2e1065",
      card: "rgba(255, 255, 255, 0.92)",
      text: "#000000",
      button: "pill",
      buttonBg: "#ffffff",
      buttonText: "#000000",
      font: "nunito",
      nameFont: "nunito",
      bioFont: "nunito",
    },
  },
  {
    id: "pastel-lines",
    name: "Pastel Abstract Lines",
    category: "Minimal Light",
    description: "Soft organic sweeping pastel lines on a warm cream background.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/pastel_lines.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/pastel_lines.svg') center / cover no-repeat #fffbf2",
      card: "#ffffff",
      text: "#292524",
      button: "pill",
      buttonBg: "#f6b8a2",
      buttonText: "#292524",
      font: "comfortaa",
      nameFont: "comfortaa",
      bioFont: "comfortaa",
    },
  },
  {
    id: "retro-sunburst",
    name: "Retro Sunburst",
    category: "Vintage",
    description: "70s vintage radial sunburst rays in muted teal, amber, and terracotta.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/retro_sunburst.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/retro_sunburst.svg') center / cover no-repeat #f4e8cf",
      card: "#fbf6ec",
      text: "#1c1917",
      button: "solid",
      buttonBg: "#2d5d55",
      buttonText: "#fbf6ec",
      font: "bebas",
      nameFont: "bebas",
      bioFont: "bebas",
    },
  },
  {
    id: "psychedelic-waves",
    name: "Psychedelic Waves",
    category: "Vibrant Waves",
    description: "Dreamy flowing pastel waves of sky blue, peach, and blush pink.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/psychedelic_waves.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/psychedelic_waves.svg') center / cover no-repeat #fef8f0",
      card: "#ffffff",
      text: "#1e1b4b",
      button: "pill",
      buttonBg: "#98d2e8",
      buttonText: "#1e1b4b",
      font: "galindo",
      nameFont: "galindo",
      bioFont: "galindo",
    },
  },
  {
    id: "neon-cyberpunk",
    name: "Neon Cyberpunk",
    category: "Dark Neon",
    description: "High-contrast dark grid with glowing cyan and hot magenta neon aura.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/neon_cyberpunk.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/neon_cyberpunk.svg') center / cover no-repeat #0a0a16",
      card: "#13132b",
      text: "#00f0ff",
      button: "outline",
      buttonBg: "#ff007f",
      buttonText: "#ffffff",
      font: "bungee",
      nameFont: "bungee",
      bioFont: "bungee",
    },
  },
  {
    id: "tropical-botanica",
    name: "Tropical Botanica",
    category: "Nature",
    description: "Deep emerald rainforest background with subtle leaf vectors and green accents.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/tropical_botanica.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/tropical_botanica.svg') center / cover no-repeat #09261e",
      card: "#0e3a2f",
      text: "#ecfdf5",
      button: "pill",
      buttonBg: "#1db954",
      buttonText: "#ffffff",
      font: "lato",
      nameFont: "lato",
      bioFont: "lato",
    },
  },
  {
    id: "glassmorphism-obsidian",
    name: "Glassmorphism Obsidian",
    category: "Glassmorphism",
    description: "Dark obsidian canvas with glowing ambient blurred mesh orbs and frosted glass elements.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/glassmorphism_orbs.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/glassmorphism_orbs.svg') center / cover no-repeat #0d1117",
      card: "rgba(255, 255, 255, 0.08)",
      text: "#f3f4f6",
      button: "pill",
      buttonBg: "#7c3aed",
      buttonText: "#ffffff",
      font: "montserrat",
      nameFont: "montserrat",
      bioFont: "montserrat",
    },
  },
  {
    id: "sunset-gradient",
    name: "Sunset Wave Gradient",
    category: "Modern Creative",
    description: "Vibrant golden hour coral-to-purple gradient with translucent wave overlays.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/sunset_gradient.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/sunset_gradient.svg') center / cover no-repeat #ff7e5f",
      card: "#ffffff",
      text: "#4c1d95",
      button: "pill",
      buttonBg: "#8a2387",
      buttonText: "#ffffff",
      font: "pacifico",
      nameFont: "pacifico",
      bioFont: "pacifico",
    },
  },
  {
    id: "minimal-terrazzo",
    name: "Minimal Terrazzo",
    category: "Minimal Light",
    description: "Elegant warm beige Italian terrazzo pattern with teal and terracotta confetti.",
    bgImageUrl: "https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/minimal_terrazzo.svg",
    theme: {
      bg: "url('https://ncyjdhpbigwlroniwnsz.supabase.co/storage/v1/object/public/theme-assets/minimal_terrazzo.svg') center / cover no-repeat #f7f4ef",
      card: "#ffffff",
      text: "#1f2937",
      button: "pill",
      buttonBg: "#3d5a80",
      buttonText: "#ffffff",
      font: "raleway",
      nameFont: "raleway",
      bioFont: "raleway",
    },
  },
];
