/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ExplorepricingRouteImport } from './routes/explorepricing'
import { Route as PlandetailRouteImport } from './routes/plandetail'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProanalyticsRouteImport } from './routes/proanalytics'
import { Route as AuthModeRouteImport } from './routes/auth.$mode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorepricingRoute = ExplorepricingRouteImport.update({
  id: '/explorepricing',
  path: '/explorepricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlandetailRoute = PlandetailRouteImport.update({
  id: '/plandetail',
  path: '/plandetail',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProanalyticsRoute = ProanalyticsRouteImport.update({
  id: '/proanalytics',
  path: '/proanalytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthModeRoute = AuthModeRouteImport.update({
  id: '/auth/$mode',
  path: '/auth/$mode',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/dashboard': typeof DashboardRoute
  '/explorepricing': typeof ExplorepricingRoute
  '/plandetail': typeof PlandetailRoute
  '/pricing': typeof PricingRoute
  '/proanalytics': typeof ProanalyticsRoute
  '/auth/$mode': typeof AuthModeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/dashboard': typeof DashboardRoute
  '/explorepricing': typeof ExplorepricingRoute
  '/plandetail': typeof PlandetailRoute
  '/pricing': typeof PricingRoute
  '/proanalytics': typeof ProanalyticsRoute
  '/auth/$mode': typeof AuthModeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/dashboard': typeof DashboardRoute
  '/explorepricing': typeof ExplorepricingRoute
  '/plandetail': typeof PlandetailRoute
  '/pricing': typeof PricingRoute
  '/proanalytics': typeof ProanalyticsRoute
  '/auth/$mode': typeof AuthModeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/dashboard'
    | '/explorepricing'
    | '/plandetail'
    | '/pricing'
    | '/proanalytics'
    | '/auth/$mode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/dashboard'
    | '/explorepricing'
    | '/plandetail'
    | '/pricing'
    | '/proanalytics'
    | '/auth/$mode'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/dashboard'
    | '/explorepricing'
    | '/plandetail'
    | '/pricing'
    | '/proanalytics'
    | '/auth/$mode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  DashboardRoute: typeof DashboardRoute
  ExplorepricingRoute: typeof ExplorepricingRoute
  PlandetailRoute: typeof PlandetailRoute
  PricingRoute: typeof PricingRoute
  ProanalyticsRoute: typeof ProanalyticsRoute
  AuthModeRoute: typeof AuthModeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorepricing': {
      id: '/explorepricing'
      path: '/explorepricing'
      fullPath: '/explorepricing'
      preLoaderRoute: typeof ExplorepricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plandetail': {
      id: '/plandetail'
      path: '/plandetail'
      fullPath: '/plandetail'
      preLoaderRoute: typeof PlandetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proanalytics': {
      id: '/proanalytics'
      path: '/proanalytics'
      fullPath: '/proanalytics'
      preLoaderRoute: typeof ProanalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$mode': {
      id: '/auth/$mode'
      path: '/auth/$mode'
      fullPath: '/auth/$mode'
      preLoaderRoute: typeof AuthModeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  DashboardRoute: DashboardRoute,
  ExplorepricingRoute: ExplorepricingRoute,
  PlandetailRoute: PlandetailRoute,
  PricingRoute: PricingRoute,
  ProanalyticsRoute: ProanalyticsRoute,
  AuthModeRoute: AuthModeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
